environment:
  nodejs_version: "6"
  matrix:
  - TYPESCRIPT: typescript@2.5.3
  - TYPESCRIPT: typescript@2.6.1
cache:
 - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - yarn run compile
  - yarn add %TYPESCRIPT%
test_script:
  - node --version
  - yarn --version
  - yarn test
build: off